

export const Nav = {
    links1: [
      { name: "Editorial", to: "/" },
      { name: "Following", to: "/following" },
    ],
    links2: [
        { name: "Current Events", to: "/t/CurrentEvents", 
        message:"Covering the latest important events, news-worthy moments and movements from around the world — from political protests to cultural celebrations. When submitting, please provide a photo description so we understand the full context of the image." },
        { name: "Wallpapers", to: "/t/Wallpapers", 
        message:""
      },
        { name: "3D Renders", to: "/t/3DRenders", 
        message:"" },
        { name: "Textures & Patterns", to: "/t/Textures&Patterns" , 
        message:""},
        { name: "Experimental", to: "/t/Experimental" , 
        message:""},
        { name: "Architecture", to: "/t/Architecture" , 
        message:""},
        { name: "Nature", to: "/t/Nature" , 
        message:""},
        { name: "Business & Work", to: "/t/Business&Work" , 
        message:""},
        { name: "Fashion", to: "/t/Fashion" , 
        message:""},
        { name: "Film", to: "/t/Film" , 
        message:""},
        { name: "Food & Drink", to: "/t/Food&Drink" , 
        message:""},
        { name: "Health & Wellness", to: "/t/Health&Wellness" , 
        message:""},
        { name: "People", to: "/t/People" , 
        message:""},
        { name: "Interiors", to: "/t/Interiors" },
        { name: "Street Photography", to: "/t/StreetPhotography" , 
        message:""},
        { name: "Travel", to: "/t/Travel" , 
        message:""},
        { name: "Animals", to: "/t/Animals" , 
        message:""},
        { name: "Spirituality", to: "/t/Spirituality" , 
        message:""},
        { name: "Arts & Culture", to: "/t/Arts&Culture" , 
        message:""},
        { name: "History", to: "/t/History" , 
        message:""},
        { name: "Athletics", to: "/t/Athletics" , 
        message:""},
      ]
}
